theme: jekyll-theme-cayman
title: GradesPaster for iSams Mark Book
description: Easily paste grades into iSams Mark Books + make links clickable in Learning Support Reports!
logo_url: /static/isamsmbp-128.png
show_downloads: false
lang: en
google_analytics: UA-120222754-1
github:
  is_project_page: false
  repository_url: https://azadisaryev.github.io/iSamsMBP/
  owner_url: https://azadisaryev.github.io/iSamsMBP/
